AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'api-gateway-test

  SAM Template for creating esource API

  '
Globals:
  Api:
    OpenApiVersion: '3.0.0'

Parameters:
  MajorVersion:
    Default: "2"
    Description: Minor version of the API
    Type: String
  MinorVersion:
    Default: "1"
    Description: Minor version of the API
    Type: String

Resources:
  CreateITTFunction:
    Properties:
      CodeUri: src/
      Handler: app.createITT
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function

  CreateITTLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ServerlessRestAPI
    - CreateITTFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateITTFunction
      Principal: apigateway.amazonaws.com

  GetTenderStatusFunction:
    Properties:
      CodeUri: src/
      Handler: app.getTenders
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function

  GetTenderStatusLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ServerlessRestAPI
    - GetTenderStatusFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetTenderStatusFunction
      Principal: apigateway.amazonaws.com

  GetTenderByIdFunction:
    Properties:
      CodeUri: src/
      Handler: app.getTenders
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function

  GetTenderByIdLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ServerlessRestAPI
    - GetTenderByIdFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetTenderByIdFunction
      Principal: apigateway.amazonaws.com

  DeleteTenderFunction:
    Properties:
      CodeUri: src/
      Handler: app.deleteTender
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function

  DeleteTenderLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ServerlessRestAPI
    - DeleteTenderFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DeleteTenderFunction
      Principal: apigateway.amazonaws.com

  ServerlessRestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './openapi3.yaml'
      Tags:
          Application: ESOURCE_API
          MAJOR_VERSION: !Ref MajorVersion
          MINOR_VERSION: !Ref MinorVersion
