AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'api-gateway-test

  Sample SAM Template for api-gateway-test

  '
Globals:
  Api:
    OpenApiVersion: '3.0.1'

Parameters:
  MajorVersion:
    Default: "2"
    Description: Minor version of the API
    Type: String
  MinorVersion:
    Default: "1"
    Description: Minor version of the API
    Type: String

Resources:
  GetUsersFunction:
    Properties:
      CodeUri: src/
      Handler: app.getAllUsers
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function

  GetUsersLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ServerlessRestAPI
    - GetUsersFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetUsersFunction
      Principal: apigateway.amazonaws.com

  GetUserFunction:
    Properties:
      CodeUri: src/
      Handler: app.getUser
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function

  GetUserLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
    - ServerlessRestAPI
    - GetUserFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetUserFunction
      Principal: apigateway.amazonaws.com

  ServerlessRestAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: default
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './openapi3.yaml'
      Tags:
          Application: ESOURCE_API
          MAJOR_VERSION: !Ref MajorVersion
          MINOR_VERSION: !Ref MinorVersion
